version: '2'

networks:
  back-tier:
    driver: bridge

services:
  application:
    build:
      context: ./application
      dockerfile: Dockerfile
    image: iot-handson_application
    volumes:
        - ./application/:/usr/src/app
        - /usr/src/app/node_modules
    ports:
      - 3000:3000
    networks:
      - back-tier
  device:
    build:
      context: ./device
      dockerfile: Dockerfile
    image: iot-handson_device
    volumes:
        - ./device/:/usr/src/app
        - /usr/src/app/node_modules
    ports:
      - 3001:3001
    networks:
      - back-tier
    depends_on:
      - application
